// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcpeseyhecsbydcmdmjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjcGVzZXloZWNzYnlkY21kbWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODcyNzUsImV4cCI6MjA2MjQ2MzI3NX0.fZ4GaZayHbaWnxIQGZGUkPcZg5V2fwGzrZZE-abSXnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);